apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: {{ template "taiga.name" . }}
    chart: {{ template "taiga.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.rabbitmq.replicaCount }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "taiga.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "taiga.name" . }}
        release: {{ .Release.Name }}
        taiga.service: rabbit
    spec:
      containers:
        - name: rabbit
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          ports:
            - containerPort: 5672
              protocol: TCP
          resources:
{{ toYaml .Values.rabbitmq.resources | indent 12 }}
    {{- with .Values.rabbitmq.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.rabbitmq.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.rabbitmq.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
