---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    taiga.service: rabbit
  annotations:
    app: taiga
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - port: {{ .Values.rabbitmq.service.port }}
      targetPort: 5672
      protocol: TCP
      name: "5672"
  selector:
    taiga.service: rabbit
status:
  loadBalancer: {}
