apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: {{ template "taiga.name" . }}
    chart: {{ template "taiga.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    taiga.service: redis
  annotations:
    app: taiga
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
      name: "6379"
  selector:
    app: {{ template "taiga.name" . }}
    release: {{ .Release.Name }}
    taiga.service: redis
