---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    taiga.service: taiga-media
  name: {{ .Chart.Name }}-media
spec:
  accessModes:
  - {{ .Values.taiga.media.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.taiga.media.capacity | quote }}
status: {}
